services:
  shopee-affiliate:
    build: ./playwright-service
    container_name: shopee-affiliate
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      HEADLESS: "false"
      SERVICE_API_KEY: ${SERVICE_API_KEY}
      STORAGE_STATE_PATH: ./storage/storageState.json
      ZALO_BOT_TOKEN: ${ZALO_BOT_TOKEN}
      ZALO_WEBHOOK_SECRET: ${ZALO_WEBHOOK_SECRET}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - ./playwright-service/storage:/app/storage
    networks:
      - shared_net

networks:
  shared_net:
    external: true
